### ISSUE TITLE
Delete devel branch?

### ISSUE THREAD

**Issue by traversaro** [robotology/whole-body-estimators#161]
I noticed that there is a devel branch of the repo, even if it is not used neither in the robotology-superbuild nor it is up-to-date, and all the development is ongoing on the master branch. Perhaps to avoid confusion we could delete this branch?

**Comment by traversaro** [comment]
@HosameldinMohamed

**Comment by HosameldinMohamed** [comment]
> Perhaps to avoid confusion we could delete this branch?

I totally agree!

**Comment by traversaro** [comment]
Great, thanks!
