### ISSUE TITLE
[WholeBodyDynamics] change logic of attaching FTs when both AnalogServer and MultipleAnalogServer interfaces are implemented

### ISSUE THREAD

**Issue by HosameldinMohamed** [robotology/whole-body-estimators#170]
When using `WholeBodyDynamics` to attach FT sensors in the gazebo plugin `gazebo_yarp_forcetorque` directly, without `multipleanalogsernsorsserver`, it considers the sensor as both AnalogServer and MultipleAnalogSensorServer device, and attaches it twice.

Maybe we could change the logic and do like what we did with the IMU (using a CMake option `HW_USE_MAS_IMU`)?

**Comment by HosameldinMohamed** [comment]
CC @traversaro @GiulioRomualdi @CarlottaSartore

**Comment by GiulioRomualdi** [comment]
Can we completely drop analog?

**Comment by HosameldinMohamed** [comment]
> Can we completely drop analog?

Would be cleaner for sure!

**Comment by traversaro** [comment]
> Can we completely drop analog?

I totally agree, after https://github.com/robotology/icub-models/issues/198 we should be ready to do that, at least for FT sensors.

**Comment by HosameldinMohamed** [comment]
`IAnalogSensor` is removed from the devices used for iCub FTs

https://github.com/robotology/icub-main/pull/928

**Comment by HosameldinMohamed** [comment]
> Can we completely drop analog?

@traversaro is handling it in #179

**Comment by traversaro** [comment]
> > Can we completely drop analog?
> 
> @traversaro is handling it in #179

Good point, I guess that PR also closes this issue, right?
