### ISSUE TITLE
Port WholeBodyDynamics device from codyco_modules

### ISSUE THREAD

**Issue by prashanthr05** [robotology/whole-body-estimators#3]
A refactoring would also be desirable to have proper maintenance.

**Comment by traversaro** [comment]
Probably you will need to coordinate with @fjandrad that is working on the device as well.

**Comment by traversaro** [comment]
PR open at https://github.com/robotology/whole-body-estimators/pull/16.  To avoid  work in the future, I start also to transfer all the wholeBodyDynamics-related issue from the other repo to this one.

**Comment by prashanthr05** [comment]
The PR https://github.com/robotology/whole-body-estimators/pull/16 was merged into devel.

Closing this issue.
