### ISSUE TITLE
fbe-analogsens device does not start with the latest version of YARP

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/whole-body-estimators#4]
I tried to run the device as explained in the [README](https://github.com/robotology/whole-body-estimators/blob/devel/devices/baseEstimatorV1/README.md). However it does not start
I think that the problem is the same described in https://github.com/robotology/codyco-modules/issues/277
@prashanthr05

**Comment by prashanthr05** [comment]
Fixed in https://github.com/robotology/whole-body-estimators/commit/be07a5146c9e92b2255cb159062a5ab3177410aa
