### ISSUE TITLE
Document the added variables to use the temperature coefficients

### ISSUE THREAD

**Issue by fjandrad** [robotology/whole-body-estimators#50]
The PR https://github.com/robotology/whole-body-estimators/pull/45 adds the options to use temperature coefficients and offline estimated offset. We will detail the usage of this functions in the wiki in this repo.

**Comment by fjandrad** [comment]
Documetation has been added in this [wiki](https://github.com/robotology/whole-body-estimators/wiki/How-to-use-the-temperature-coefficients-and-offset-compensation.) 
Feel free to check and signal if something is not clear. @prashanthr05 @traversaro @S-Dafarra

**Comment by traversaro** [comment]
I strongly suggest **not** to use the wiki for this kind of  documentation, but rather make sure that the docs are stored in the repo, eventually as a `.md` file containing exactly the same content of the  wiki page, but inside of the repo. The rationale behind that is that so you always know which version of the software the documentation refers to. For example, let's say that in the future I want to add a new parameters, and I add the software in the `devel` branch, and  it gets merged in `master` only after six months. When I should update the docs, if they are stored in the wiki? If I update it before  `master` have changed, people using the `master` branch may be confused. All this problems are avoided if the docs are put inside the repo.

**Comment by fjandrad** [comment]
Pending to move the wiki to a docs folder

**Comment by prashanthr05** [comment]
> Pending to move the wiki to a docs folder

I have done this in https://github.com/robotology/whole-body-estimators/pull/84

**Comment by HosameldinMohamed** [comment]
PR #84 is merged with `devel`

I close this issue.
