### ISSUE TITLE
Update README to add references to wholebodydynamics

### ISSUE THREAD

**Issue by traversaro** [robotology/whole-body-estimators#55]
The README still contains only references `baseEstimatorV1` , and there is no documentation (or link to documentation) of `wholebodydynamics`.

**Comment by traversaro** [comment]
We should also make sure that from the README are reachable: 
* The documentation of the parameters supported by `wholebodydynamics` , that are currently documented in a doxygen block of the `WholeBodyDynamicsDevice` class
* The docs added in https://github.com/robotology/whole-body-estimators/issues/50
* I noticed that we left behind in codyco-modules  the document https://github.com/robotology-legacy/codyco-modules/blob/master/doc/force_control_on_icub.md, perhaps it could make sense to bring it back and store it in this repo.

**Comment by prashanthr05** [comment]
@HosameldinMohamed if we could update the READMEs and close this issue, we can make a new release of the `whole-body-estimators`.

**Comment by prashanthr05** [comment]
This is done as a part of https://github.com/robotology/whole-body-estimators/pull/84.

**Comment by HosameldinMohamed** [comment]
PR #84 is merged to `devel`.

I close this issue.
