### ISSUE TITLE
Clarify velocity representation

### ISSUE THREAD

**Issue by diegoferigo** [robotology/whole-body-estimators#81]
The `baseEstimatorV1` devices streams the estimated quantities to the `/base-estimator/floating_base/state:o` port. The methods called are the following, where a minimal documentation exists:

https://github.com/robotology/whole-body-estimators/blob/9608ba9ccb2262ae18244328c4efa1b5aafe5583/devices/baseEstimatorV1/include/baseEstimatorV1.h#L427-L444

It is not clear, however, what is the velocity representation used. Is it the mixed representation as defined in [Multibody Dynamics Notation](https://pure.tue.nl/ws/portalfiles/portal/139293126/A_Multibody_Dynamics_Notation_Revision_2_.pdf)?

cc @prashanthr05 @traversaro

**Comment by prashanthr05** [comment]
Yes, internally iDynTree free-floating frame Jacobians are used to compute the velocity assuming rigid contacts at the feet. And these Jacobians are computed using mixed-velocity representations.

**Comment by diegoferigo** [comment]
Thanks @prashanthr05 for the confirmation!
